### ISSUE TITLE
similar projects to generate native GUI from CLI app? qt, gtk, wx, tcl/tk, ...

### ISSUE THREAD

**Issue by milahu** [TheJaredWilcurt/UGUI#12]
hey, nice project : )

im looking for similar projects, that can generate native GUIs

ideas?

why: one limitation of html interfaces is the "choose file" dialog.
i could use electron, but i want to avoid the javascript-overhead
(alternatives: [tauri](https://github.com/tauri-apps/tauri/discussions/1579), [nodegui](https://docs.nodegui.org/docs/api/generated/classes/qfiledialog/), [flutter](https://pub.dev/packages/file_picker), ...)

for python, there are [Gooey](https://github.com/chriskiehl/Gooey) and [Cli2Gui](https://github.com/FHPythonUtils/Cli2Gui) and [magicgui](https://napari.org/magicgui)
but im looking for a language agnostic solution

i suggest to list such "similar projects" in the readme
for example [cli-wrapper-ui](https://github.com/chrisczach/cli-wrapper-ui) also renders to html
or should we start an `awesome-cli2gui` list?

**Comment by TheJaredWilcurt** [comment]
https://xpda.net
